### PR TITLE
Validate proxy mesh config

### LINKED ISSUE #539: need validation for proxymeshconfig
We currently have validation for the routing proto, but lack validation for the ProxyMeshConfig which also touches some aspects of Envoy config. For example, users can set the cluster connect timeout via the proxy mesh config. These fields need to be validated/sanitized to ensure that incorrect values ( negative timeouts) don't creep in (this would cause Envoy to crash).

### PR DESCRIPTION
**Pull request by kyessenov**
Fixes #539

### CODE REVIEW

File: model/validation_test.go [hunk 1]
```diff
@@ -0,0 +1,696 @@
...
+		},
+			valid: false},
+	}
+	for _, c := range cases {
+		if got := ValidateDestinationPolicy(c.in); (got == nil) != c.valid {
+			t.Errorf("Failed: got valid=%t but wanted valid=%v: %v", got == nil, c.valid, got)
+		}
+	}
+}
+
```
Comment (kyessenov) [inline model/validation_test.go]: everything above just got moved (git failed to identify a diff)

File: model/validation.go [hunk 2]
```diff
@@ -669,3 +661,89 @@ func ValidateDestinationPolicy(msg proto.Message) error {
...
+		errs = multierror.Append(errs, multierror.Prefix(err, "invalid refresh delay:"))
+	}
+
+	if err := validateDuration(mesh.ConnectTimeout); err != nil {
+		errs = multierror.Append(errs, multierror.Prefix(err, "invalid connect timeout:"))
+	}
+
+	if mesh.AuthCertsPath == "" {
+		errs = multierror.Append(errs, errors.New("invalid auth certificates path"))
+	}
```
Comment (lookuptable) [inline model/validation.go]: Can we also verify `mesh.AuthPolicy`? Then we can probably get rid of the check here: https://github.com/istio/manager/blob/master/proxy/envoy/discovery.go#L489

File: model/validation.go [hunk 3]
```diff
@@ -669,3 +661,89 @@ func ValidateDestinationPolicy(msg proto.Message) error {
 
 	return errs
 }
+
+func validateProxyAddress(hostAddr string) error {
```
Comment (ayj) [inline model/validation.go]: https://golang.org/pkg/net/#SplitHostPort could be used here.

File: model/validation.go [hunk 4]
```diff
@@ -669,3 +661,89 @@ func ValidateDestinationPolicy(msg proto.Message) error {
...
+	}
+	return nil
+}
+
+func validateDuration(pd *duration.Duration) error {
+	dur, err := ptypes.Duration(pd)
+	if err != nil {
+		return err
+	}
+	if dur <= 0 {
```
Comment (ayj) [inline model/validation.go]: Maybe a good idea to check max duration here as well? This would need to be specified as paramter to this function but would help catch fat-fingering Xs instead of Xs when hand editing config maps.

Comment (kyessenov) [inline model/validation.go]: @rshriram what are you good upper bounds for durations in this config?

File: model/validation.go (hunk 2 above)
Comment (kyessenov) [inline model/validation.go]: thanks, good call.

File: model/validation.go (hunk 3 above)
Comment (kyessenov) [inline model/validation.go]: hm, not sure about ipv6 support in envoy.

Comment (ayj) [inline model/validation.go]: The current code doesn't validate the host part either. Maybe something like the following?

```golang
host, port, err := net.SplitHostPort(hostAddr)
if err != { return err }

if _, err := net.ResolveIPAddr("ip6", host); err == nil {
    return fmt.Errorf("ipv6 not supported: %v", err)
}
// port validation, etc.
```

Comment (kyessenov) [inline model/validation.go]: I couldn't quite see if golang checks for DNS names. Envoy can use either IPv4 or DNS host but not IPv6.

Comment (ayj) [inline model/validation.go]: Yup. That's why I reversed the check to be anything *not* ipv6. The documentation says checking against hostname isn't recommending since DNS can resolve to more than one address.

Comment (kyessenov) [inline model/validation.go]: I don't think we should be resolving DNS names in validation. First, DNS resolvers might be different between golang and envoy. Second, DNS can change the IP assignment.

Comment (ayj) [inline model/validation.go]: Agreed. Maybe the following? Either way, host validation is a different issue from splitting up the hostAddr into host/port tuple./

```golang
if ip := net.ParseIP(host); ip != nil && ip.To4() == nil {
    return fmt.Errors("ipv6 address: %v, host)
}
```

**Comment by kyessenov** [comment]
jenkins rebuild manager/presubmit

File: model/validation.go (hunk 3 above)
Comment (kyessenov) [inline model/validation.go]: Not sure what you suggest. "my-name" and "10.0.0.10" are both valid envoy hosts. This will just detect the second case.

Comment (ayj) [inline model/validation.go]: The snippet above returns an error if the host is IPv6. Anything else (IPv4 or DNS name) should be okay. I believe that is what you wanted to validate?

See https://play.golang.org/p/zsWMAoutrB

Comment (kyessenov) [inline model/validation.go]: since we already had functions to validate both host and ipv4, I added host validation.

File: proxy/envoy/config.go [hunk 5]
```diff
@@ -196,10 +196,7 @@ func applyInboundAuth(listener *Listener, mesh *proxyconfig.ProxyMeshConfig) *Li
 	case proxyconfig.ProxyMeshConfig_NONE:
 	case proxyconfig.ProxyMeshConfig_MUTUAL_TLS:
 		listener.SSLContext = buildListenerSSLContext(mesh.AuthCertsPath)
-	default:
```
Comment (andraxylia) [inline proxy/envoy/config.go]: Not a good idea to remove the default case.

File: model/validation.go (hunk 4 above)
Comment (rshriram) [inline model/validation.go]: upper and lower bounds.
drain/parent shutdown duration: >1s <1hr?
refresh delay: >1s <10m ?
connect timeout: >1ms <30s
